version: 2
updates:
  - package-ecosystem: gradle
    directory: /android/app
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
